import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import './globals.scss'

import Header from '@/components/ui/header';

const dmSans = DM_Sans({ 
  subsets: ['latin'],
  weight: [
    '400',
  ]
})

export const metadata: Metadata = {
  title: 'apportal.io',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={dmSans.className}>
        <Header/>
        <main className="flex flex-col items-center justify-between">
          {children}
        </main>
      </body>
    </html>
  )
}
