import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import './globals.scss'
import Main from '@/components/ui/main';

import Header from '@/components/ui/header';

const dmSans = DM_Sans({ 
  subsets: ['latin'],
  weight: [
    '400',
  ]
})

export const metadata: Metadata = {
  title: 'apportal.io',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={dmSans.className}>
        <Header/>
        <Main>
          {children}
        </Main>
      </body>
    </html>
  )
}
